We will look at pandas functions to explore a dataset see how to make changes to it.

In [4]:
#load packages
import os
import pandas as pd

In [11]:
#get working directory

#in R: getwd()

os.getcwd()

'/Users/meltemodabas/github/meltemod/R-to-Python'

In [22]:
#change working directory

#in R: setwd("")

os.chdir(r'/Users/meltemodabas/github/meltemod/R-to-Python')

In [17]:
df = pd.read_csv("data/kaggle-fifa/players_15.csv")

In [21]:
#look at the first 5 rows

#in R: head(df)

df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,...,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,30,1984-01-23,180,80,Netherlands,FC Bayern München,...,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3
3,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Z. Ibrahimović,Zlatan Ibrahimović,32,1981-10-03,195,95,Sweden,Paris Saint-Germain,...,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3
4,167495,https://sofifa.com/player/167495/manuel-neuer/...,M. Neuer,Manuel Neuer,28,1986-03-27,193,92,Germany,FC Bayern München,...,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3

In [23]:
#get all column names

#in R: names(df)

df.columns

Index(['sofifa_id', 'player_url', 'short_name', 'long_name', 'age', 'dob',
       'height_cm', 'weight_kg', 'nationality', 'club_name',
       ...
       'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb'],
      dtype='object', length=106)

In [24]:
#drop columns

#in R
# drops <- c("x", "z")
# df[ , !(names(df) %in% drops)]

df.drop(columns = ['player_url'])

,sofifa_id,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,league_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,Spain Primera Division,...,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3
1,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,Spain Primera Division,...,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3
2,9014,A. Robben,Arjen Robben,30,1984-01-23,180,80,Netherlands,FC Bayern München,German 1. Bundesliga,...,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3
3,41236,Z. Ibrahimović,Zlatan Ibrahimović,32,1981-10-03,195,95,Sweden,Paris Saint-Germain,French Ligue 1,...,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3
4,167495,M. Neuer,Manuel Neuer,28,1986-03-27,193,92,Germany,FC Bayern München,German 1. Bundesliga,...,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,E. Redman,Ellis Redman,17,1996-09-26,187,81,Wales,Newport County,English League Two,...,37+0,38+0,38+0,38+0,37+0,40+0,41+0,41+0,41+0,40+0
16151,225509,A. Collins,Aaron Collins,17,1997-06-01,178,57,Wales,Newport County,English League Two,...,31+0,30+0,30+0,30+0,31+0,32+0,31+0,31+0,31+0,32+0
16152,217591,P. Żemło,Piotr Żemło,18,1995-07-10,190,76,Poland,Wisła Kraków,Polish T-Mobile Ekstraklasa,...,48+0,46+0,46+0,46+0,48+0,51+,53+,53+,53+,51+
16153,222947,T. Davies,Tom Davies,22,1992-04-18,180,70,England,Fleetwood Town,English League One,...,37+0,36+0,36+0,36+0,37+0,39+0,40+0,40+0,40+0,39+0
16154,201197,P. Tisdale,Paul Tisdale,41,1973-01-14,175,72,Malta,Exeter City,English League Two,...,36+0,37+0,37+0,37+0,36+0,34+0,33+0,33+0,33+0,34+0

In [25]:
#get a row count

#in R: length(df)

len(df)

16155

In [39]:
#query by conditional statement

# in R: df[df$age > 40, ]

df.query("age >= 40")

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
470,11983,https://sofifa.com/player/11983/brad-friedel/1...,B. Friedel,Brad Friedel,43,1971-05-18,188,92,United States,Tottenham Hotspur,...,31+0,33+0,33+0,33+0,31+0,31+0,35+0,35+0,35+0,31+0
795,684,https://sofifa.com/player/684/mark-schwarzer/1...,M. Schwarzer,Mark Schwarzer,41,1972-10-06,194,95,Australia,Chelsea,...,32+0,33+0,33+0,33+0,32+0,32+0,34+0,34+0,34+0,32+0
2664,135708,https://sofifa.com/player/135708/cuauhtemoc-bl...,C. Blanco,Cuauhtémoc Blanco Bravo,41,1973-01-17,177,80,Mexico,Puebla FC,...,51+0,58+0,58+0,58+0,51+0,47+0,47+0,47+0,47+0,47+0
2673,139006,https://sofifa.com/player/139006/oswaldo-sanch...,O. Sánchez,Oswaldo Javier Sánchez Ibarra,40,1973-09-21,184,84,Mexico,Santos Laguna,...,32+1,34+1,34+1,34+1,32+1,31+1,36+1,36+1,36+1,31+1
3318,188033,https://sofifa.com/player/188033/essam-el-hada...,E. El-Hadary,Essam Kamal Tawfik El Hadary,41,1973-01-15,187,85,Egypt,NaN,...,30+0,32+0,32+0,32+0,30+0,30+0,33+0,33+0,33+0,30+0
3730,136594,https://sofifa.com/player/136594/byung-ji-kim/...,Kim Byung Ji,김병지 Byung Ji Kim,44,1970-04-08,184,78,Korea Republic,Jeonnam Dragons,...,30+0,30+0,30+0,30+0,30+0,30+0,33+0,33+0,33+0,30+0
3746,140029,https://sofifa.com/player/140029/oscar-perez/1...,O. Pérez,Óscar Pérez Rojas,41,1973-02-01,170,70,Mexico,Pachuca,...,32+0,33+0,33+0,33+0,32+0,32+0,36+0,36+0,36+0,32+0
3810,161260,https://sofifa.com/player/161260/alexandr-fili...,A. Filimonov,Aleksandr Filimonov,40,1973-10-15,193,90,Russia,Arsenal Tula,...,31+0,37+0,37+0,37+0,31+0,31+0,37+0,37+0,37+0,31+0
5186,31834,https://sofifa.com/player/31834/frode-johnsen/...,F. Johnsen,Frode Johnsen,40,1974-03-17,187,79,Norway,Odds BK,...,46+0,47+0,47+0,47+0,46+0,47+0,52+0,52+0,52+0,47+0
6117,144432,https://sofifa.com/player/144432/kristian-berg...,K. Bergström,Kristian Bergström,40,1974-01-08,175,73,Sweden,Åtvidabergs FF,...,55+0,58+0,58+0,58+0,55+0,49+0,44+0,44+0,44+0,49+0
6210,165854,https://sofifa.com/player/165854/juan-carlos-h...,J. Henao,Juan Carlos Henao Valencia,42,1971-12-30,181,79,Colombia,Once Caldas,...,30+0,33+0,33+0,33+0,30+0,30+0,33+0,33+0,33+0,30+0
6959,10457,https://sofifa.com/player/10457/mattias-asper/...,M. Asper,Mattias Asper,40,1974-03-20,198,94,Sweden,Mjällby AIF,...,31+0,34+0,34+0,34+0,31+0,31+0,34+0,34+0,34+0,31+0
8011,53785,https://sofifa.com/player/53785/marcus-hahnema...,M. Hahnemann,Marcus Hahnemann,42,1972-06-15,191,100,United States,Seattle Sounders FC,...,28+0,31+0,31+0,31+0,28+0,28+0,33+0,33+0,33+0,28+0
9081,147742,https://sofifa.com/player/147742/ruslan-adzhin...,R. Adzhindzhal,Ruslan Adzhindzhal,40,1974-06-22,168,68,Russia,FC Krasnodar,...,50+0,53+0,53+0,53+0,50+0,46+0,44+0,44+0,44+0,46+0
10027,167078,https://sofifa.com/player/167078/mattias-hugos...,M. Hugosson,Mattias Hugosson,40,1974-01-24,190,88,Sweden,IFK Göteborg,...,30+0,33+0,33+0,33+0,30+0,30+0,33+0,33+0,33+0,30+0
10891,188492,https://sofifa.com/player/188492/andrea-pierob...,A. Pierobon,Andrea Pierobon,44,1969-07-19,183,79,Italy,Cittadella,...,28+0,31+0,31+0,31+0,28+0,28+0,29+0,29+0,29+0,28+0
11643,53643,https://sofifa.com/player/53643/jimmy-walker/1...,J. Walker,Jimmy Walker,40,1973-07-09,180,84,England,Peterborough United,...,32+0,34+0,34+0,34+0,32+0,31+0,33+0,33+0,33+0,31+0
13071,163569,https://sofifa.com/player/163569/steve-banks/1...,S. Banks,Steve Banks,42,1972-02-09,183,83,England,St. Johnstone FC,...,30+0,32+0,32+0,32+0,30+0,29+0,31+0,31+0,31+0,29+0
14146,139479,https://sofifa.com/player/139479/gareth-ainswo...,G. Ainsworth,Gareth Ainsworth,41,1973-05-10,178,79,England,Wycombe Wanderers,...,45+0,47+0,47+0,47+0,45+0,41+0,42+0,42+0,42+0,41+0
15964,168706,https://sofifa.com/player/168706/paul-mathers/...,P. Mathers,Paul Mathers,44,1970-01-17,183,72,Scotland,St. Mirren,...,26+0,27+0,27+0,27+0,26+0,26+0,29+0,29+0,29+0,26+0
15965,199068,https://sofifa.com/player/199068/ashley-bayes/...,A. Bayes,Ashley Bayes,42,1972-04-19,185,85,England,AFC Wimbledon,...,27+0,29+0,29+0,29+0,27+0,27+0,29+0,29+0,29+0,27+0
16145,11728,https://sofifa.com/player/11728/barry-richards...,B. Richardson,Barry Richardson,44,1969-08-05,185,77,England,Wycombe Wanderers,...,27+0,28+0,28+0,28+0,27+0,27+0,30+0,30+0,30+0,27+0
16154,201197,https://sofifa.com/player/201197/paul-tisdale/...,P. Tisdale,Paul Tisdale,41,1973-01-14,175,72,Malta,Exeter City,...,36+0,37+0,37+0,37+0,36+0,34+0,33+0,33+0,33+0,34+0

In [43]:
df.query("nationality == 'Mexico'")

# in R: df[df$nationality > 'Mexico', ]

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
104,169416,https://sofifa.com/player/169416/carlos-vela/1...,C. Vela,Carlos Alberto Vela Garrido,25,1989-03-01,177,75,Mexico,Real Sociedad,...,58+1,58+1,58+1,58+1,58+1,51+1,46+1,46+1,46+1,51+1
164,170369,https://sofifa.com/player/170369/giovani-dos-s...,G. dos Santos,Giovani dos Santos Ramírez,25,1989-05-11,175,74,Mexico,Villarreal CF,...,57+1,55+1,55+1,55+1,57+1,51+1,43+1,43+1,43+1,51+1
174,178224,https://sofifa.com/player/178224/javier-hernan...,J. Hernández,Javier Hernández Balcázar,26,1988-06-01,175,71,Mexico,Real Madrid,...,54+1,53+1,53+1,53+1,54+1,51+1,46+1,46+1,46+1,51+1
270,140233,https://sofifa.com/player/140233/guillermo-och...,G. Ochoa,Francisco Guillermo Ochoa Magaña,28,1985-07-13,185,78,Mexico,Málaga CF,...,32+1,33+1,33+1,33+1,32+1,31+1,33+1,33+1,33+1,31+1
413,173432,https://sofifa.com/player/173432/hector-moreno...,H. Moreno,Héctor Alfredo Moreno Herrera,26,1988-01-17,184,80,Mexico,RCD Espanyol,...,70+0,72+0,72+0,72+0,70+0,74+0,78+0,78+0,78+0,74+0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15307,222082,https://sofifa.com/player/222082/raul-mendiola...,R. Mendiola,Raúl Mendiola,20,1994-05-18,173,68,Mexico,LA Galaxy,...,42+0,39+0,39+0,39+0,42+0,37+0,35+0,35+0,35+0,37+0
15430,223577,https://sofifa.com/player/223577/pablo-mascare...,P. Mascareñas,Pablo Mascareñas,24,1989-08-04,171,69,Mexico,Club Atlas,...,53+0,51+0,51+0,51+0,53+0,51+0,50+0,50+0,50+0,51+0
15439,182656,https://sofifa.com/player/182656/leonardo-garc...,L. García,Leonardo García,27,1986-12-11,179,72,Mexico,U.N.A.M.,...,49+0,48+0,48+0,48+0,49+0,52+0,52+0,52+0,52+0,52+0
15528,216298,https://sofifa.com/player/216298/miguel-angel-...,M. Cancela,Miguel Ángel Cancela,21,1993-05-21,170,65,Mexico,Tiburones Rojos de Veracruz,...,51+0,46+0,46+0,46+0,51+0,52+0,51+0,51+0,51+0,52+0
15613,222545,https://sofifa.com/player/222545/jorge-sartiag...,J. Sartiaguin,Jorge Luis Sartiaguín Godoy,20,1993-08-24,172,70,Mexico,Deportivo Toluca,...,53+0,53+0,53+0,53+0,53+0,53+0,54+0,54+0,54+0,53+0

In [45]:
df.query("rdm == rwb")

# in R: df[which(df$rdm == df$rwb), ]

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,...,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,30,1984-01-23,180,80,Netherlands,FC Bayern München,...,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3
5,176580,https://sofifa.com/player/176580/luis-suarez/1...,L. Suárez,Luis Alberto Suárez Díaz,27,1987-01-24,181,81,Uruguay,FC Barcelona,...,67+3,67+3,67+3,67+3,67+3,62+3,57+3,57+3,57+3,62+3
10,156616,https://sofifa.com/player/156616/franck-ribery...,F. Ribéry,Franck Bilal Ribéry,31,1983-04-07,170,72,France,FC Bayern München,...,63+2,63+2,63+2,63+2,63+2,53+2,44+2,44+2,44+2,53+2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16131,216445,https://sofifa.com/player/216445/sean-noble/15...,S. Noble,Sean Noble,18,1996-03-20,183,75,Republic of Ireland,Bray Wanderers,...,42+0,42+0,42+0,42+0,42+0,39+0,38+0,38+0,38+0,39+0
16132,222523,https://sofifa.com/player/222523/james-pollard...,J. Pollard,James Pollard,17,1997-05-07,180,70,England,Bradford City,...,43+0,43+0,43+0,43+0,43+0,45+0,47+0,47+0,47+0,45+0
16134,184860,https://sofifa.com/player/184860/pawel-socha/1...,P. Socha,Paweł Socha,22,1991-08-13,184,84,Poland,Górnik Łęczna,...,26+0,26+0,26+0,26+0,26+0,25+0,27+0,27+0,27+0,25+0
16140,224927,https://sofifa.com/player/224927/tom-smith/150002,T. Smith,Tom Smith,18,1996-04-16,180,70,England,Swindon Town,...,43+0,43+0,43+0,43+0,43+0,43+0,42+0,42+0,42+0,43+0
16147,220939,https://sofifa.com/player/220939/luke-pilling/...,L. Pilling,Luke Pilling,16,1997-07-25,180,69,Wales,Tranmere Rovers,...,28+0,28+0,28+0,28+0,28+0,28+0,28+0,28+0,28+0,28+0

In [50]:
#look up a range of cells (does not take column names)

#in R: df[1:10, 6:10]

df.iloc[:10, 5:10]

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,...,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,30,1984-01-23,180,80,Netherlands,FC Bayern München,...,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3
3,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Z. Ibrahimović,Zlatan Ibrahimović,32,1981-10-03,195,95,Sweden,Paris Saint-Germain,...,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3
4,167495,https://sofifa.com/player/167495/manuel-neuer/...,M. Neuer,Manuel Neuer,28,1986-03-27,193,92,Germany,FC Bayern München,...,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3
5,176580,https://sofifa.com/player/176580/luis-suarez/1...,L. Suárez,Luis Alberto Suárez Díaz,27,1987-01-24,181,81,Uruguay,FC Barcelona,...,67+3,67+3,67+3,67+3,67+3,62+3,57+3,57+3,57+3,62+3
6,41,https://sofifa.com/player/41/andres-iniesta-lu...,Iniesta,Andrés Iniesta Luján,30,1984-05-11,170,65,Spain,FC Barcelona,...,76+3,77+3,77+3,77+3,76+3,70+3,63+3,63+3,63+3,70+3
7,183277,https://sofifa.com/player/183277/eden-hazard/1...,E. Hazard,Eden Hazard,23,1991-01-07,173,74,Belgium,Chelsea,...,62+2,64+2,64+2,64+2,62+2,54+2,46+2,46+2,46+2,54+2
8,7826,https://sofifa.com/player/7826/robin-van-persi...,R. van Persie,Robin van Persie,30,1983-08-06,187,71,Netherlands,Manchester United,...,60+3,63+3,63+3,63+3,60+3,54+3,48+3,48+3,48+3,54+3
9,121944,https://sofifa.com/player/121944/bastian-schwe...,B. Schweinsteiger,Bastian Schweinsteiger,29,1984-08-01,183,79,Germany,FC Bayern München,...,81+2,84+2,84+2,84+2,81+2,81+2,79+2,79+2,79+2,81+2

In [55]:
#look up a range of cells (takes column names *only*)

#in R: df[1:10, c("short_name", "long_name")]

df.loc[:10, ["short_name", "long_name"]]

           short_name                            long_name
0            L. Messi       Lionel Andrés Messi Cuccittini
1   Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro
2           A. Robben                         Arjen Robben
3      Z. Ibrahimović                   Zlatan Ibrahimović
4            M. Neuer                         Manuel Neuer
5           L. Suárez             Luis Alberto Suárez Díaz
6             Iniesta                 Andrés Iniesta Luján
7           E. Hazard                          Eden Hazard
8       R. van Persie                     Robin van Persie
9   B. Schweinsteiger               Bastian Schweinsteiger
10          F. Ribéry                  Franck Bilal Ribéry

In [57]:
#check data types 

#in R: str(df)

df.dtypes

sofifa_id      int64
player_url    object
short_name    object
long_name     object
age            int64
               ...
lb            object
lcb           object
cb            object
rcb           object
rb            object
Length: 106, dtype: object

In [59]:
#get summary stats

#in R: summary(df)

df.describe()

,sofifa_id,age,height_cm,weight_kg,league_rank,overall,potential,value_eur,wage_eur,international_reputation,...,mentality_penalties,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
count,16155.000000,16155.000000,16155.000000,16155.000000,15916.000000,16155.000000,16155.000000,1.615500e+04,16155.000000,16155.000000,...,16155.000000,0.0,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000
mean,189284.184525,24.776230,181.083627,75.474342,1.378424,63.830393,68.350108,1.060882e+06,13056.453110,1.122501,...,49.648344,NaN,45.009037,47.656639,45.885918,15.869514,15.511668,15.354875,15.504735,15.998514
std,39749.261554,4.625321,6.618974,6.891796,0.736796,7.169896,6.580610,2.819128e+06,23488.182571,0.396263,...,14.552244,NaN,17.915206,18.743105,18.145497,17.576799,16.414173,16.010498,16.585081,17.983209
min,2.000000,16.000000,155.000000,50.000000,1.000000,40.000000,40.000000,0.000000e+00,0.000000,1.000000,...,20.000000,NaN,20.000000,20.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,178042.500000,21.000000,176.000000,70.000000,1.000000,59.000000,64.000000,1.200000e+05,2000.000000,1.000000,...,39.000000,NaN,25.000000,25.000000,25.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,200841.000000,24.000000,181.000000,75.000000,1.000000,64.000000,68.000000,3.500000e+05,5000.000000,1.000000,...,50.000000,NaN,46.000000,52.000000,49.000000,11.000000,11.000000,11.000000,10.000000,10.000000
75%,214346.000000,28.000000,186.000000,80.000000,2.000000,68.000000,73.000000,8.250000e+05,10000.000000,1.000000,...,61.000000,NaN,61.000000,64.000000,62.000000,13.000000,14.000000,13.000000,13.000000,13.000000
max,225562.000000,44.000000,204.000000,110.000000,4.000000,93.000000,95.000000,1.005000e+08,550000.000000,5.000000,...,95.000000,NaN,90.000000,91.000000,95.000000,88.000000,87.000000,92.000000,90.000000,90.000000

In [60]:
#find unique values of a column

#in R: unique(df$age)

df.age.unique()

array([27, 29, 30, 32, 28, 23, 31, 24, 25, 22, 26, 34, 33, 35, 21, 36, 20,
       19, 37, 43, 41, 18, 38, 17, 39, 40, 16, 44, 42])

In [68]:
#check number of unique values in a column

#in R: length(unique(df$age))

len(df.age.unique())

29

In [69]:
#or
df.age.nunique( )

29

In [62]:
#get a sample of the dataset

#in R:
# keep <- sample(ceiling(nrow(df)*.25), 1:nrow(df), FALSE)
# df[keep, ]

df.sample(frac=.25)

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
11996,205961,https://sofifa.com/player/205961/alejandro-rod...,Alejandro Gorrín,Alejandro Rodríguez Gorrín,20,1993-08-01,185,70,Spain,Wellington Phoenix,...,59+0,61+0,61+0,61+0,59+0,59+0,59+0,59+0,59+0,59+0
11734,176798,https://sofifa.com/player/176798/mattias-ostbe...,M. Östberg,Mattias Östberg,36,1977-08-24,189,86,Sweden,Djurgårdens IF,...,47+0,53+0,53+0,53+0,47+0,53+0,60+0,60+0,60+0,53+0
15103,225246,https://sofifa.com/player/225246/francesco-ake...,F. Akermann Silva,Francesco Akermann Silva,19,1995-03-07,180,75,Venezuela,Unión La Calera,...,42+0,41+0,41+0,41+0,42+0,39+0,38+0,38+0,38+0,39+0
2719,158592,https://sofifa.com/player/158592/german-montoy...,G. Montoya,Marcelo Germán Montoya,31,1983-01-23,185,83,Argentina,Independiente,...,32+0,32+0,32+0,32+0,32+0,32+0,33+0,33+0,33+0,32+0
14897,224776,https://sofifa.com/player/224776/uros-celcer/1...,U. Celcer,Uroš Celcer,25,1989-04-07,182,78,Slovenia,Ross County FC,...,54+0,50+0,50+0,50+0,54+0,54+0,56+0,56+0,56+0,54+0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8467,214231,https://sofifa.com/player/214231/marcelo-jorqu...,M. Jorquera,Marcelo Jorquera,21,1992-10-13,178,75,Chile,Deportes Iquique,...,65+0,62+0,62+0,62+0,65+0,63+0,63+0,63+0,63+0,63+0
3770,148625,https://sofifa.com/player/148625/david-mendes-...,D. Mendes da Silva,David Mendes da Silva,31,1982-08-04,186,77,Netherlands,Panathinaikos FC,...,68+0,69+0,69+0,69+0,68+0,66+0,65+0,65+0,65+0,66+0
910,194229,https://sofifa.com/player/194229/hugo-mallo-no...,Hugo Mallo,Hugo Mallo Novegil,23,1991-06-22,173,69,Spain,RC Celta,...,75+0,73+0,73+0,73+0,75+0,75+0,73+0,73+0,73+0,75+0
1200,206545,https://sofifa.com/player/206545/manuel-trigue...,Manu Trigueros,Manuel Trigueros Muñoz,22,1991-10-17,178,70,Spain,Villarreal CF,...,69+0,71+0,71+0,71+0,69+0,66+0,63+0,63+0,63+0,66+0
5159,202530,https://sofifa.com/player/202530/alvaro-rey-va...,Alvaro Rey,Álvaro Rey Vázquez,24,1989-07-11,185,77,Spain,AD Alcorcón,...,52+0,51+0,51+0,51+0,52+0,47+0,42+0,42+0,42+0,47+0

In [74]:
#check total number of null values for each column

#in R: lapply(df, function(x) { length(which(is.na(x))) })

df.isnull().sum()

club_name                 239
league_name               239
league_rank               239
release_clause_eur      16155
player_tags             14919
team_position             239
team_jersey_number        239
loaned_from             15243
joined                   1151
contract_valid_until      239
nation_position         15074
nation_jersey_number    15074
pace                     1775
shooting                 1775
passing                  1775
dribbling                1775
defending                1775
physic                   1775
gk_diving               14380
gk_handling             14380
gk_kicking              14380
gk_reflexes             14380
gk_speed                14380
gk_positioning          14380
player_traits            9556
mentality_composure     16155
dtype: int64

In [ ]:
#list only those with null values greater than zero

#in R: 
# null_values = lapply(df, function(x) { length(which(is.na(x))) })
# null_values[which(null_values > 0)]

null_values = df.isnull().sum()
null_values[null_values > 0]

In [77]:
#rename column
#in R: names(df)[names(df) == "sofifa_id"] <- "FID"

df.rename(columns = {"sofifa_id": "FID"})

,FID,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,...,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,30,1984-01-23,180,80,Netherlands,FC Bayern München,...,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3
3,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Z. Ibrahimović,Zlatan Ibrahimović,32,1981-10-03,195,95,Sweden,Paris Saint-Germain,...,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3
4,167495,https://sofifa.com/player/167495/manuel-neuer/...,M. Neuer,Manuel Neuer,28,1986-03-27,193,92,Germany,FC Bayern München,...,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,https://sofifa.com/player/220806/ellis-redman/...,E. Redman,Ellis Redman,17,1996-09-26,187,81,Wales,Newport County,...,37+0,38+0,38+0,38+0,37+0,40+0,41+0,41+0,41+0,40+0
16151,225509,https://sofifa.com/player/225509/aaron-collins...,A. Collins,Aaron Collins,17,1997-06-01,178,57,Wales,Newport County,...,31+0,30+0,30+0,30+0,31+0,32+0,31+0,31+0,31+0,32+0
16152,217591,https://sofifa.com/player/217591/piotr-zemlo/1...,P. Żemło,Piotr Żemło,18,1995-07-10,190,76,Poland,Wisła Kraków,...,48+0,46+0,46+0,46+0,48+0,51+,53+,53+,53+,51+
16153,222947,https://sofifa.com/player/222947/tom-davies/15...,T. Davies,Tom Davies,22,1992-04-18,180,70,England,Fleetwood Town,...,37+0,36+0,36+0,36+0,37+0,39+0,40+0,40+0,40+0,39+0
16154,201197,https://sofifa.com/player/201197/paul-tisdale/...,P. Tisdale,Paul Tisdale,41,1973-01-14,175,72,Malta,Exeter City,...,36+0,37+0,37+0,37+0,36+0,34+0,33+0,33+0,33+0,34+0

In [89]:
#get median values, grouped by another column

#in R:
#library(dplyr)
# df %>%
#    group_by(nationality) %>%
#    summarize(median_age = median(age))

df.groupby("nationality")['age'].median()

nationality
Albania              24.0
Algeria              25.0
Angola               24.5
Antigua & Barbuda    23.0
Argentina            25.0
                     ...
Uzbekistan           28.0
Venezuela            26.0
Wales                23.0
Zambia               23.0
Zimbabwe             25.0
Name: age, Length: 149, dtype: float64

In [92]:
#get correlation between values

#in R: corr(df)

df.corr(method = 'pearson')

,sofifa_id,age,height_cm,weight_kg,league_rank,overall,potential,value_eur,wage_eur,international_reputation,...,mentality_penalties,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
sofifa_id,1.000000,-0.697896,-0.094996,-0.164712,-0.046543,-0.388496,-0.076603,-0.168085,-0.239751,-0.374139,...,-0.150305,NaN,-0.119975,-0.113933,-0.093604,-0.070842,-0.078050,-0.072206,-0.081404,-0.069984
age,-0.697896,1.000000,0.085429,0.211942,-0.045947,0.436976,-0.072417,0.123850,0.195714,0.277557,...,0.132347,NaN,0.158064,0.145385,0.122019,0.092458,0.101170,0.095343,0.107999,0.090986
height_cm,-0.094996,0.085429,1.000000,0.766291,0.037870,0.050819,0.014917,0.019091,0.029582,0.050119,...,-0.292724,NaN,0.037352,0.018252,0.003512,0.348764,0.346815,0.343080,0.346524,0.345892
weight_kg,-0.164712,0.211942,0.766291,1.000000,0.009887,0.123992,0.015527,0.043671,0.061731,0.084284,...,-0.227797,NaN,0.030988,0.012957,-0.004027,0.337191,0.335765,0.332982,0.336338,0.333946
league_rank,-0.046543,-0.045947,0.037870,0.009887,1.000000,-0.246777,-0.231447,-0.132561,-0.191666,-0.119929,...,-0.075520,NaN,-0.065619,-0.057351,-0.055491,-0.016840,-0.014785,-0.022322,-0.023042,-0.016740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
goalkeeping_diving,-0.070842,0.092458,0.348764,0.337191,-0.016840,-0.006846,-0.035506,0.013693,0.007759,0.008410,...,-0.534776,NaN,-0.382174,-0.414968,-0.396032,1.000000,0.965764,0.961639,0.965462,0.971391
goalkeeping_handling,-0.078050,0.101170,0.346815,0.335765,-0.014785,-0.001172,-0.033718,0.015733,0.009043,0.008512,...,-0.530044,NaN,-0.384996,-0.417145,-0.398667,0.965764,1.000000,0.960053,0.965065,0.965769
goalkeeping_kicking,-0.072206,0.095343,0.343080,0.332982,-0.022322,-0.006270,-0.037169,0.014575,0.008431,0.009023,...,-0.526553,NaN,-0.381214,-0.413647,-0.395181,0.961639,0.960053,1.000000,0.959941,0.962224
goalkeeping_positioning,-0.081404,0.107999,0.346524,0.336338,-0.023042,0.003398,-0.032625,0.016516,0.011687,0.010315,...,-0.530255,NaN,-0.379256,-0.412215,-0.393194,0.965462,0.965065,0.959941,1.000000,0.965825
goalkeeping_reflexes,-0.069984,0.090986,0.345892,0.333946,-0.016740,-0.007090,-0.034995,0.013963,0.007326,0.006593,...,-0.533815,NaN,-0.384001,-0.417155,-0.397885,0.971391,0.965769,0.962224,0.965825,1.000000

In [93]:
#perform binning with speficic number of bins

#in R:
#library(dplyr)
#df %>% mutate(df = cut(age, breaks = 3))

pd.cut(df['age'], bins = 5).value_counts()

(21.6, 27.2]      7063
(15.972, 21.6]    4590
(27.2, 32.8]      3481
(32.8, 38.4]       988
(38.4, 44.0]        33
Name: age, dtype: int64

In [ ]:
#find largest values of a column 

#in R:
#library(dplyr)
#df %>% top_n(6, age)

df.nlargest(6, “Age”)

In [103]:
df.loc[:10,"player_url"]

0     https://sofifa.com/player/158023/lionel-messi/...
1     https://sofifa.com/player/20801/c-ronaldo-dos-...
2     https://sofifa.com/player/9014/arjen-robben/15...
3     https://sofifa.com/player/41236/zlatan-ibrahim...
4     https://sofifa.com/player/167495/manuel-neuer/...
5     https://sofifa.com/player/176580/luis-suarez/1...
6     https://sofifa.com/player/41/andres-iniesta-lu...
7     https://sofifa.com/player/183277/eden-hazard/1...
8     https://sofifa.com/player/7826/robin-van-persi...
9     https://sofifa.com/player/121944/bastian-schwe...
10    https://sofifa.com/player/156616/franck-ribery...
Name: player_url, dtype: object

In [109]:
df.age.describe()

count    16155.000000
mean        24.776230
std          4.625321
min         16.000000
25%         21.000000
50%         24.000000
75%         28.000000
max         44.000000
Name: age, dtype: float64

In [118]:
df.groupby('nationality')['age'].median()

nationality
Albania              24.0
Algeria              25.0
Angola               24.5
Antigua & Barbuda    23.0
Argentina            25.0
                     ...
Uzbekistan           28.0
Venezuela            26.0
Wales                23.0
Zambia               23.0
Zimbabwe             25.0
Name: age, Length: 149, dtype: float64

In [119]:
#create a new variable

#in R
#df$new <- 1
#or
#library(dplyr)
#df %>% mutate(new = 1)

df.assign(new = 1)

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,new
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,1
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,...,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,1
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,30,1984-01-23,180,80,Netherlands,FC Bayern München,...,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,1
3,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Z. Ibrahimović,Zlatan Ibrahimović,32,1981-10-03,195,95,Sweden,Paris Saint-Germain,...,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,1
4,167495,https://sofifa.com/player/167495/manuel-neuer/...,M. Neuer,Manuel Neuer,28,1986-03-27,193,92,Germany,FC Bayern München,...,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,https://sofifa.com/player/220806/ellis-redman/...,E. Redman,Ellis Redman,17,1996-09-26,187,81,Wales,Newport County,...,38+0,38+0,38+0,37+0,40+0,41+0,41+0,41+0,40+0,1
16151,225509,https://sofifa.com/player/225509/aaron-collins...,A. Collins,Aaron Collins,17,1997-06-01,178,57,Wales,Newport County,...,30+0,30+0,30+0,31+0,32+0,31+0,31+0,31+0,32+0,1
16152,217591,https://sofifa.com/player/217591/piotr-zemlo/1...,P. Żemło,Piotr Żemło,18,1995-07-10,190,76,Poland,Wisła Kraków,...,46+0,46+0,46+0,48+0,51+,53+,53+,53+,51+,1
16153,222947,https://sofifa.com/player/222947/tom-davies/15...,T. Davies,Tom Davies,22,1992-04-18,180,70,England,Fleetwood Town,...,36+0,36+0,36+0,37+0,39+0,40+0,40+0,40+0,39+0,1
16154,201197,https://sofifa.com/player/201197/paul-tisdale/...,P. Tisdale,Paul Tisdale,41,1973-01-14,175,72,Malta,Exeter City,...,37+0,37+0,37+0,36+0,34+0,33+0,33+0,33+0,34+0,1

In [122]:
df = df.assign(new = 2) #change df

In [124]:
df.assign(half_age = df.age / df.new)

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,new,half_age
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,2,13.5
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,...,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,2,14.5
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,30,1984-01-23,180,80,Netherlands,FC Bayern München,...,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,2,15.0
3,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Z. Ibrahimović,Zlatan Ibrahimović,32,1981-10-03,195,95,Sweden,Paris Saint-Germain,...,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,2,16.0
4,167495,https://sofifa.com/player/167495/manuel-neuer/...,M. Neuer,Manuel Neuer,28,1986-03-27,193,92,Germany,FC Bayern München,...,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,2,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16150,220806,https://sofifa.com/player/220806/ellis-redman/...,E. Redman,Ellis Redman,17,1996-09-26,187,81,Wales,Newport County,...,38+0,38+0,37+0,40+0,41+0,41+0,41+0,40+0,2,8.5
16151,225509,https://sofifa.com/player/225509/aaron-collins...,A. Collins,Aaron Collins,17,1997-06-01,178,57,Wales,Newport County,...,30+0,30+0,31+0,32+0,31+0,31+0,31+0,32+0,2,8.5
16152,217591,https://sofifa.com/player/217591/piotr-zemlo/1...,P. Żemło,Piotr Żemło,18,1995-07-10,190,76,Poland,Wisła Kraków,...,46+0,46+0,48+0,51+,53+,53+,53+,51+,2,9.0
16153,222947,https://sofifa.com/player/222947/tom-davies/15...,T. Davies,Tom Davies,22,1992-04-18,180,70,England,Fleetwood Town,...,36+0,36+0,37+0,39+0,40+0,40+0,40+0,39+0,2,11.0
16154,201197,https://sofifa.com/player/201197/paul-tisdale/...,P. Tisdale,Paul Tisdale,41,1973-01-14,175,72,Malta,Exeter City,...,37+0,37+0,36+0,34+0,33+0,33+0,33+0,34+0,2,20.5